### ISSUE TITLE
install: support custom role name

### ISSUE THREAD

**Issue by mpareja** [eventide-project/postgres-message-store#1]
The [uninstall.sh script](https://github.com/eventide-project/postgres-message-store/blob/master/database/uninstall.sh#L12) allows the role name to be customized. The [install.sh script](https://github.com/eventide-project/postgres-message-store/blob/master/database/install.sh#L28) and associated [SQL script](https://github.com/eventide-project/postgres-message-store/blob/master/database/user/role.sql#L3) do not.

Is this intentional? Are you opposed to allowing the role name to be customized?

**Comment by sbellware** [comment]
@mpareja There’s no way that I’ve found to allow the role name to be specified to the SQL scripts from the external environment. So, not a design opinion really, but more of a constraint that has been beyond our reach and control.

If you find a way, please point it out!

PS: Lots of people have posted hypothetical solutions to us over the years. So to be clear: If you find a way, please point it out... with a demonstrative script or test! :)

**Comment by mpareja** [comment]
The `uninstall.sh` version works because you're using dynamically generated SQL. Are you opposed to a similar approach?

**Comment by sbellware** [comment]
@mpareja That's not the database user that's installed into the database. That's the database user that has the authority to install (or uninstall) the user.

**Comment by sbellware** [comment]
PS: The only way to do this that I can see is to build a code generator that would customize the scripts using string templates and interpolation. Which, by the way, is exactly the solution we have now. Except that instead of forcing the user to indulge some custom tool that we provide, we free the user to use the tools that they're already practiced with, like Vim, or sed, or SublimeText, or... :)

**Comment by mpareja** [comment]
> @mpareja That's not the database user that's installed into the database. That's the database user that has the authority to install (or uninstall) the user.

Are you sure about this? The [usage of that variable](https://github.com/eventide-project/postgres-message-store/blob/master/database/uninstall.sh#L43) drops the role. The usage is also an example of the dynamic SQL I was referring to. (i.e. use bash variable interpolation to generate SQL.)

**Comment by mpareja** [comment]
@sbellware I spiked out an approach involving passing variables to `psql`. It works great when assigning privileges. I couldn't figure out how to get the variables to work inside of a `do` block, so I used dynamic SQL with bash interpolation for the role creation - similar to the database and role dropping found in `uninstall.sh`.

https://github.com/mpareja/postgres-message-store/tree/custom-role

**Comment by sbellware** [comment]
@mpareja Part of what your seeing is dead code that was supposed to have been removed when we stopped allowing the control of the role.

So, the solution you've come up with solves one problem and creates another. It's a solution we disqualified as a result of user persona analysis.

Database operations affordances need to reflect the ways and means of database operations people and their work. And that means SQL scripts on disk that can be audited and executed either wholly or in part.

So, we can't afford to obscure SQL script code by embedding it in strings. We want it to be browsable. We want the interaction cost of gathering understanding to be as low as possible by meeting data ops people where they expect to be met.

We don't want to get in the way of the data ops person's imperatives for auditing, verifying, and testing somebody else's DDL. And so the DDL is offered as the plain old SQL scripts that are standard operating procedure of data ops work.

We don't want to provide an opaque code generator. We want to provide the transparent code.

**Comment by mpareja** [comment]
Okay, sounds like sticking to usable SQL scripts is an important constraint.

We could consider a transform? The following feels a tad "programming by coincidence". Given we control the inputs, the transforms, and could write some tests, it might be enough. (untested pseudo-code ahead)

```
cat database/user/role.sql | sed 's/message_store/TheCustomUser/' | psql ....
cat database/user/privileges.sql | sed 's/message_store/TheCustomUser/' | psql ....
```

The approach would (happen to) work for `role.sql` and `privileges.sql` because the `message_store` token isn't used to reference anything other than the role name.

---

> Part of what your seeing is dead code that was supposed to have been removed when we stopped allowing the control of the role.

I'm a little confused by this sentence. Which code are you hoping to eradicate, and _who_ ought to no longer be allowed to do _what_ with the role?

**Comment by sbellware** [comment]
@mpareja The dead code is the stuff that allows the user to be specified in the uninstall script. It's vestigial code dating from an implementation that didn't work. Most other script files had that user control code removed. The user control code in the uninstall should have been removed when removed this ability from a handful of other script files some time ago.

The transform is exactly how we'd expect it to be done. But it's the user's choice whether or not to do it. So, specializations and customizations of that sort are up to the user. And as you've demonstrated, the user already has all the needed tools to make such adaptations.

The scripts that we provide are a baseline of the message store database, but they're ultimately a starting point and guidance. If a user needs to make changes, they're expected to do so, and then to own their adaptations of the code.

**Comment by mpareja** [comment]
The role name is part of a server-wide namespace, like the database name. If the logic is sound, shouldn't we also take away the ability to customize the database name?

I was striving to make the installation and removal of the message store a bit more "hermetic". If I need to customize the database name, perhaps that is because there is more than one message store running on the same database server. And if there is more than one message store running on the same database server, I wouldn't want to share the same role.

**Comment by sbellware** [comment]
Allowing for a different database name is just a token affordance. It's not terribly practical for more significant data operations. It's more useful for development than operations, and it's important to make sure that we're not looking at database operations through the lens of developer presumptions. Controlling the database name is readily within reach using the tools of the trade of Postgres operations and operators, so we offer it as a matter of affordance.

When the needs are beyond the basic starting point offered by the stock database operations scripts, a database operator will make the changes to the scripts that they need to make for the needs of their own topology.

The scripts are _suggestive_ not _prescriptive_. The only thing that's prescriptive is the published contract.

**Comment by mpareja** [comment]
> Allowing for a different database name is just a token affordance. It's not terribly practical for more significant data operations. It's more useful for development than operations, and it's important to make sure that we're not looking at database operations through the lens of developer presumptions. 

I agree and think the creation of a database _all together_ is a developer affordance. In reality, a database operator is likely to be thinking about other important factors like which disk to place the data and transaction logs on.

I'll go ahead and close this issue - despite being a developer longing for the convenience of a custom role!

**Comment by sbellware** [comment]
> In reality, a database operator is likely to be thinking about other important factors like which disk to place the data and transaction logs on.

Indeed. Amongst many other factors.
